### ISSUE TITLE
Serve indexed items through the search endpoint

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#107]
- [ ] Return the items in an unordered (but ideally consistent) unpaginated list

Depends on #94 and #95.

**Comment by GiancarloFusiello** [comment]
In order to index items from the content store service, is it possible to get:
- the url of the context store api and endpoints to request data from
- an example response or schema for each endpoint
- a list of items/attributes to index

**Comment by giorgiosironi** [comment]
For the first two points, I think the best example is this:
```
curl -v http://unstable--dummy-api.libero.pub/blog-articles/items
curl -v http://unstable--dummy-api.libero.pub/scholarly-articles/items
```
This is the `dummy-api` configured with two content stores and running in a real environment. We will mimic this to set it up in the local docker-compose.yml.

For the last point, I'd index both `id` and `service` because they need to come out in the response. Though what we really need so far is to store them, not necessarily to also index them as there are no queries yet that can filter on these fields (nor I'm sure if there will be).
