### ISSUE TITLE
Index items from content APIs

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#95]
Produce a CLI command(?) to index all items from a specified content API service.

- [ ] Fetch all items from [content APIs `/items`](https://docs.google.com/document/d/1jMJ4NxzHiBroNerUbiNWn5H01kgaPRvfRELr1WDvPRY/edit#heading=h.b6sm8juxstw9)
- [ ] Index the items (probably service prefix and ID; in ElasticSearch?)
- [ ] Deploy
  - [ ] Run Elasticsearch
  - [ ] Index content from the dummy API

**Comment by GiancarloFusiello** [comment]
Is this depending on itself?

**Comment by thewilkybarkid** [comment]
Example doc: https://github.com/libero/sample-configuration/blob/b007be1827f484a364f6e4ceca171f40c6a9998c/.docker/api/data/scholarly-articles/article1/1.xml#L5-L9

**Comment by GiancarloFusiello** [comment]
Moving comments that were accidentally added to the wrong issue.

@GiancarloFusiello commented:
>In order to index items from the content store service, is it possible to get:
>* the url of the context store api and endpoints to request data from
>* an example response or schema for each endpoint
>* a list of items/attributes to index

@giorgiosironi commented:
>For the first two points, I think the best example is this:

>```
>curl -v http://unstable--dummy-api.libero.pub/blog-articles/items
>curl -v http://unstable--dummy-api.libero.pub/scholarly-articles/items
>```
>This is the `dummy-api` configured with two content stores and running in a real environment. We will mimic this to set it up in the local docker-compose.yml.

>For the last point, I'd index both `id` and `service` because they need to come out in the response. Though what we really need so far is to store them, not necessarily to also index them as there are no queries yet that can filter on these fields (nor I'm sure if there will be).

**Comment by GiancarloFusiello** [comment]
@giorgiosironi @thewilkybarkid If I'm looking at the curl commands above, `dummy-api` is the name of the service. `/blog-articles` and `/scholarly-articles` are paths. `/items` seems redundant unless `/items` only returns ids and a path would return the full objects? If so, this could also be done by sending filters in requests e.g. `/blog-articles?filters=id`.

Here is the current response data from `http://unstable--dummy-api.libero.pub/blog-articles/items`:
```xml
<item-list xmlns="http://libero.pub">
    <item-ref id="post1" service="blog-articles"/>
</item-list>
```
Is `service=` being used to determine the type of content? If so, could this be inferred from where it was requested or be renamed to `content-type=`, for example?

I'm also curious to understand the roadmap of this approach of just sending an id and service to be indexed by search. Is the idea of sending an id that a second request would then be made to get the content?

Finally, I think it would be easier for search, or any other service, to make requests to the api-gateway, or some other proxy, rather than requesting data directly from a service? For example, `http://unstable--api-gateway.libero.pub/blog-posts` for a list of blog-posts.

@BlueReZZ @diversemix @nlisgo I would like to know your thoughts if you don't mind chipping in.

**Comment by giorgiosironi** [comment]
> If I'm looking at the curl commands above, `dummy-api` is the name of the service. `/blog-articles` and `/scholarly-articles` are paths. 

This is true in the context of `dummy-api`, but if it was a real service (rather than a dummy), it would be two independent services. Clients like `search` hopefully should be isolated from the actual implementation of `blog-articles`/`scholarly-articles`, this may mean that we see them as separate as the lowest common denominator (in the spirit of the Interface Segregation Principle) even if in some testing case they will be backed by the same code.

> `/items` seems redundant unless `/items` only returns ids and a path would return the full objects? If so, this could also be done by sending filters in requests e.g. `/blog-articles?filters=id`.

The [spec](https://docs.google.com/document/d/1jMJ4NxzHiBroNerUbiNWn5H01kgaPRvfRELr1WDvPRY/edit#) says this will [return ids](https://github.com/libero/schemas/blob/master/api/content/item-list.rng#L8), correct. The spec doesn't have an endpoint with multiple items being included in full, one of the reasons probably that this would be very large. For example a [single item can be almost 1MB](https://github.com/elifesciences/elife-article-xml/blob/master/articles/elife-18566-v2.xml).

**Comment by giorgiosironi** [comment]
> Here is the current response data from `http://unstable--dummy-api.libero.pub/blog-articles/items` [...] Is `service=` being used to determine the type of content? If so, could this be inferred from where it was requested or be renamed to `content-type=`, for example?

In this particular case it could be inferred, but the attribute coming from the XML is part of a specified schema for the XML document, so it should be a more stable value to rely upon with respect to exploding a URL by `/` and taking some parts of it.

> I'm also curious to understand the roadmap of this approach of just sending an id and service to be indexed by search. Is the idea of sending an id that a second request would then be made to get the content?

Yes, as soon as `search` needs to index something more than id and service, one additional request per item should be performed to retrieve each one in full. In terms of roadmap, this may mean that these requests and the indexing process should eventually be performed by background processes and a local queue of "items to index" as doing that serially is typically very slow. For example, eLife's search service takes [~30 minutes](https://alfred.elifesciences.org/job/prod-search/162/) to perform a full reindexing, despite the fact that it is only a few thousand items and most of the work is performed by parallelized workers fed from a queue one item at a time.

> Finally, I think it would be easier for search, or any other service, to make requests to the api-gateway, or some other proxy, rather than requesting data directly from a service? For example, `http://unstable--api-gateway.libero.pub/blog-posts` for a list of blog-posts.

Yes: this is how it should work. The contract with the `search` configuration should probably be just a list of URLs (called services URLs), but they will be:
```
http://unstable--api-gateway.libero.pub/blog-posts
http://unstable--api-gateway.libero.pub/scholarly-articles
```

**Comment by thewilkybarkid** [comment]
> @giorgiosironi @thewilkybarkid If I'm looking at the curl commands above, `dummy-api` is the name of the service. `/blog-articles` and `/scholarly-articles` are paths. `/items` seems redundant ...

Dummy API is an application that appears as multiple services. `blog-articles` and `scholarly-articles` are service IDs, `items` in a path inside the service. (Services always have a `/ping` path too.)

> Is `service=` being used to determine the type of content? If so, could this be inferred from where it was requested or be renamed to `content-type=`, for example?

Content type has a different meaning to service. (A `scholary-article` service could include `research-article`, `feature-article`, `correction` content types.)

**Comment by GiancarloFusiello** [comment]
The closing above was accidental.
